package requests

import (
    "os"
    "errors"
    "net/http"
)

func validateJWT(jwt string) error {
    str, err := UserStrapiRequest("users/me", jwt)

    if err != nil ||str != "" {
        return errors.New("validation failled")
    }

    return nil
}

func GetUserJWT(w http.ResponseWriter, r *http.Request) (string, error) {
    var jwt string
    if jwt = r.Header.Get("Authorization"); jwt == "" {
        http.Redirect(w, r, "/login", http.StatusMovedPermanently) 
        return "", errors.New("missing auth");
    }
    
    if err := validateJWT(jwt); err != nil {
        http.Redirect(w, r, "/login", http.StatusMovedPermanently) 
        return "", err;
    }

    return jwt, nil
}

func getAppKey() string {
    appkey, err := os.ReadFile(".api_token")
    if err != nil {
        println("Missing .api_token, it should be generated by deploy.sh, error:", err)
    }

    return string(appkey)
}
