package requests

import (
	"errors"
	"net/http"
	"os"
	"strings"
)

func validateJWT(jwt string) error {
	str, err := UserStrapiRequest("users/me", jwt)

	if err != nil || str != "" {
		return errors.New("validation failled")
	}

	return nil
}

// Check for jwt in cookies and headers
func GetUserJWT(r *http.Request) (string, error) {
	if cookie, err := r.Cookie("jwt"); err == nil {
		return cookie.Value, nil
	}

	authHeader := r.Header.Get("Authorization")
	if authHeader != "" {
		parts := strings.Split(authHeader, " ")
		if len(parts) == 2 && parts[0] == "Bearer" {
			token := parts[1]
			if err := validateJWT(token); err != nil {
				return "", err
			}
			return token, nil
		}
		return "", errors.New("invalid authorization header")
	}

	return "", errors.New("missing auth")
}

func getAppKey() string {
	appkey, err := os.ReadFile(".api_token")
	if err != nil {
		println("Missing .api_token, it should be generated by deploy.sh, error:", err)
	}

	return string(appkey)
}
