package requests

import (
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
)

func getAppKey() string {
    appkey, err := os.ReadFile(".api_token")
    if err != nil {
        println("Missing .api_token, it should be generated by deploy.sh, error:", err)
    }

    return string(appkey)
}

func ServerStrapiRequest(endpoint string) (string, error) {
    client := &http.Client{}
    url := "http://127.0.0.1:1337/api/" + endpoint

    req, err := http.NewRequest("GET", url, nil)
    if err != nil {
        return "", err
    }

    auth := fmt.Sprintf("Bearer %s", strings.TrimSuffix(getAppKey(), "\n"))
    req.Header.Add("Authorization", auth)

    resp, err := client.Do(req)
    if err != nil {
        return "", err
    }

    if strings.Split(resp.Status, " ")[0] == "200" {
        respBody, _ := io.ReadAll(resp.Body)
        println("200 OK: api_token validated")
        return string(respBody), nil 
    }     

    return "", errors.New("Strapi endpoint sent " + resp.Status)
}

func GetUserJWT(r *http.Request) (string, error) {
    var auth string
    if auth = r.Header.Get("Authorization"); auth == "" {
        return "", errors.New("authorization missing")
    }

    return strings.Split(auth, " ")[1], nil
}

func UserStrapiRequest(endpoint string, jwt string) (string, error) {
    client := &http.Client{}
    url := "http://127.0.0.1:1337/api/" + endpoint

    req, err := http.NewRequest("GET", url, nil)
    if err != nil {
        return "", err
    }

    auth := fmt.Sprintf("Bearer %s", jwt)
    req.Header.Add("Authorization", auth)

    resp, err := client.Do(req)
    if err != nil {
        return "", err
    }

    if strings.Split(resp.Status, " ")[0] == "200" {
        respBody, _ := io.ReadAll(resp.Body)
        println("200 OK: api_token validated")
        return string(respBody), nil 
    }     

    return "", errors.New("Strapi endpoint sent " + resp.Status)
}
